# Generated by Django 3.2.12 on 2022-02-02 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20220202_1158'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reviev',
            new_name='Review',
        ),
    ]
